#
# Copyright 2015, Tongji Operating System Group & elastos.org
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#

DIRECTORIES += src/plat/A20/machine

PLAT_C_SOURCES += machine/hardware.c \
                  machine/l2cache.c

ifdef DEBUG
    PLAT_C_SOURCES += machine/io.c
endif
