#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_1LEVEL)        += sel4test-1level

# list of libraries the app needs to build
sel4test-1level-y                          = common libsel4 libmuslc libsel4vka libcpio libelf \
                                      libsel4allocman \
                                      libsel4platsupport libsel4platsupport libsel4muslcsys \
                                      libsel4simple libsel4vspace libsel4utils libutils

# add the tests app  as a component so that we can elf load it
sel4test-1level-components-y += sel4test-hi
sel4test-1level-components = $(addprefix $(STAGE_BASE)/bin/, $(sel4test-1level-components-y))

sel4test-1level: export COMPONENTS=${sel4test-1level-components}
sel4test-1level: ${sel4test-1level-components-y} kernel_elf $(sel4test-1level-y)
