#
# Copyright 2015, Tongji Operating System Group & elastos.org
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

libs-$(CONFIG_MANTLE_FILESYSTEM) += libLinker
libLinker: common
