#
# Copyright 2015, Tongji Operating System Group & elastos.org
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
#

libs-$(CONFIG_LIB_ZENER_HELPERS) += libZenerHelpers
libZenerHelpers: common libsel4 $(libc)
