#
# Copyright 2015, Tongji Operating System Group & elastos.org
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#

include ${SOURCE_ROOT}/include/plat/${PLAT}/plat/machine/Makefile
